// Tax configs
export { SENEGAL_TAX_CONFIG } from './senegal/tax-config'
export { IVORY_COAST_TAX_CONFIG } from './ivory-coast/tax-config'
export { MALI_TAX_CONFIG } from './mali/tax-config'
export { BURKINA_FASO_TAX_CONFIG } from './burkina-faso/tax-config'
export { NIGER_TAX_CONFIG } from './niger/tax-config'
export { BENIN_TAX_CONFIG } from './benin/tax-config'
export { TOGO_TAX_CONFIG } from './togo/tax-config'
export { GUINEA_BISSAU_TAX_CONFIG } from './guinea-bissau/tax-config'
export { CAMEROON_TAX_CONFIG } from './cameroon/tax-config'
export { GABON_TAX_CONFIG } from './gabon/tax-config'
export { CONGO_TAX_CONFIG } from './congo/tax-config'
export { CHAD_TAX_CONFIG } from './chad/tax-config'
export { CAR_TAX_CONFIG } from './central-african-republic/tax-config'
export { EQ_GUINEA_TAX_CONFIG } from './equatorial-guinea/tax-config'
export { COMOROS_TAX_CONFIG } from './comoros/tax-config'
export { DRC_TAX_CONFIG } from './drc/tax-config'
export { GUINEA_TAX_CONFIG } from './guinea/tax-config'

// Payroll configs
export { SENEGAL_PAYROLL_CONFIG } from './senegal/payroll-config'
export { IVORY_COAST_PAYROLL_CONFIG } from './ivory-coast/payroll-config'
export { MALI_PAYROLL_CONFIG } from './mali/payroll-config'
export { BURKINA_FASO_PAYROLL_CONFIG } from './burkina-faso/payroll-config'
export { NIGER_PAYROLL_CONFIG } from './niger/payroll-config'
export { BENIN_PAYROLL_CONFIG } from './benin/payroll-config'
export { TOGO_PAYROLL_CONFIG } from './togo/payroll-config'
export { GUINEA_BISSAU_PAYROLL_CONFIG } from './guinea-bissau/payroll-config'
export { CAMEROON_PAYROLL_CONFIG } from './cameroon/payroll-config'
export { GABON_PAYROLL_CONFIG } from './gabon/payroll-config'
export { CONGO_PAYROLL_CONFIG } from './congo/payroll-config'
export { CHAD_PAYROLL_CONFIG } from './chad/payroll-config'
export { CAR_PAYROLL_CONFIG } from './central-african-republic/payroll-config'
export { EQ_GUINEA_PAYROLL_CONFIG } from './equatorial-guinea/payroll-config'
export { COMOROS_PAYROLL_CONFIG } from './comoros/payroll-config'
export { DRC_PAYROLL_CONFIG } from './drc/payroll-config'
export { GUINEA_PAYROLL_CONFIG } from './guinea/payroll-config'
