import type { Account } from '../../core/types'

/**
 * CLASSE 8 SYSCOHADA: "Autres Charges et Autres Produits" (Hors Activités Ordinaires HAO)
 *
 * Cette classe regroupe les comptes relatifs aux opérations hors activités ordinaires,
 * incluant les cessions d'immobilisations, les charges et produits HAO, ainsi que
 * les dotations, reprises, participations et impôts sur le résultat.
 */

export const CLASSE_8_ACCOUNTS: Account[] = [
  // CLASSE 81: Valeurs comptables des cessions d'immobilisations
  {
    number: '81',
    labelFr: 'Valeurs comptables des cessions d\'immobilisations',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '812',
    labelFr: 'Valeurs comptables des cessions d\'immobilisations incorporelles',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '813',
    labelFr: 'Valeurs comptables des cessions d\'immobilisations corporelles',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '816',
    labelFr: 'Valeurs comptables des cessions d\'immobilisations financières',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 82: Produits des cessions d'immobilisations
  {
    number: '82',
    labelFr: 'Produits des cessions d\'immobilisations',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '822',
    labelFr: 'Produits des cessions d\'immobilisations incorporelles',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '823',
    labelFr: 'Produits des cessions d\'immobilisations corporelles',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '826',
    labelFr: 'Produits des cessions d\'immobilisations financières',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 83: Charges hors activités ordinaires
  {
    number: '83',
    labelFr: 'Charges hors activités ordinaires',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '831',
    labelFr: 'Charges HAO constatées',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '832',
    labelFr: 'Pertes sur risques HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '835',
    labelFr: 'Dons et libéralités accordés',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '836',
    labelFr: 'Abandons de créances consentis',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '838',
    labelFr: 'Charges HAO diverses',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 84: Produits hors activités ordinaires
  {
    number: '84',
    labelFr: 'Produits hors activités ordinaires',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '841',
    labelFr: 'Produits HAO constatés',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '845',
    labelFr: 'Dons et libéralités obtenus',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '846',
    labelFr: 'Abandons de créances obtenus',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '848',
    labelFr: 'Produits HAO divers',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 85: Dotations HAO
  {
    number: '85',
    labelFr: 'Dotations HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '851',
    labelFr: 'Dotations aux provisions réglementées',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '852',
    labelFr: 'Dotations aux amortissements HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '853',
    labelFr: 'Dotations aux provisions HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '858',
    labelFr: 'Autres dotations HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 86: Reprises HAO
  {
    number: '86',
    labelFr: 'Reprises HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '861',
    labelFr: 'Reprises de provisions réglementées',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '862',
    labelFr: 'Reprises d\'amortissements HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '863',
    labelFr: 'Reprises de provisions HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '868',
    labelFr: 'Autres reprises HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 87: Participation des travailleurs
  {
    number: '87',
    labelFr: 'Participation des travailleurs',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '871',
    labelFr: 'Participation légale aux bénéfices',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 88: Subventions d'équilibre
  {
    number: '88',
    labelFr: 'Subventions d\'équilibre',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '881',
    labelFr: 'Subventions d\'équilibre reçues',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '882',
    labelFr: 'Subventions d\'équilibre versées',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 89: Impôts sur le résultat
  {
    number: '89',
    labelFr: 'Impôts sur le résultat',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '891',
    labelFr: 'Impôts sur les bénéfices de l\'exercice',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '892',
    labelFr: 'Rappels d\'impôts sur résultats antérieurs',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '895',
    labelFr: 'Crédit d\'impôt',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    number: '899',
    labelFr: 'Impôts sur le résultat - participation',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
]

export default CLASSE_8_ACCOUNTS
