import type { Account } from '../../core/types'

export const CLASSE_1_ACCOUNTS: Account[] = [
  // 10 - CAPITAL
  {
    number: '10',
    label: 'Capital',
    labelFr: 'Capital',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '101',
    label: 'Share Capital',
    labelFr: 'Capital social',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1011',
    label: 'Share Capital Subscribed Not Called',
    labelFr: 'Capital souscrit non appelé',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1012',
    label: 'Share Capital Called Not Paid',
    labelFr: 'Capital appelé non versé',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1013',
    label: 'Share Capital Called and Paid',
    labelFr: 'Capital appelé versé',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '104',
    label: 'Share Premiums',
    labelFr: 'Primes liées au capital',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '105',
    label: 'Revaluation Differences',
    labelFr: 'Écarts de réévaluation',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '106',
    label: 'Reserves',
    labelFr: 'Réserves',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1061',
    label: 'Statutory Reserve',
    labelFr: 'Réserve légale',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1062',
    label: 'Reserve for Undistributed Earnings',
    labelFr: 'Réserve pour bénéfices non distribués',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1063',
    label: 'Reserve for Own Shares',
    labelFr: 'Réserve pour actions propres',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1064',
    label: 'Reserve for Fluctuation in Exchange Rates',
    labelFr: 'Réserve pour fluctuation des cours de change',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1065',
    label: 'Reserve for Price Fluctuation',
    labelFr: 'Réserve pour fluctuation des prix',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1066',
    label: 'Contingency Reserve',
    labelFr: 'Réserve de contingence',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1067',
    label: 'Regulated Reserve',
    labelFr: 'Réserve réglementée',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1068',
    label: 'Other Reserves',
    labelFr: 'Autres réserves',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '109',
    label: 'Shareholders Capital Subscribed Not Called',
    labelFr: 'Actionnaires capital souscrit non appelé',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 11 - RETAINED EARNINGS
  {
    number: '11',
    label: 'Retained Earnings',
    labelFr: 'Report à nouveau',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '111',
    label: 'Retained Earnings Credit',
    labelFr: 'Report à nouveau créditeur',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '119',
    label: 'Retained Earnings Debit',
    labelFr: 'Report à nouveau débiteur',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 12 - NET INCOME
  {
    number: '12',
    label: 'Net Income',
    labelFr: 'Résultat net',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '120',
    label: 'Net Income Pending Allocation',
    labelFr: 'Résultat net en instance d\'affectation',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '121',
    label: 'Profit',
    labelFr: 'Bénéfice',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '129',
    label: 'Loss',
    labelFr: 'Perte',
    classNumber: 1,
    category: 'BALANCE_SHEET_EQUITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 13 - INVESTMENT SUBSIDIES
  {
    number: '13',
    label: 'Investment Subsidies',
    labelFr: 'Subventions d\'investissement',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '131',
    label: 'Subsidies from Public Bodies',
    labelFr: 'Subventions des pouvoirs publics',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '138',
    label: 'Other Investment Subsidies',
    labelFr: 'Autres subventions d\'investissement',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 14 - REGULATED PROVISIONS
  {
    number: '14',
    label: 'Regulated Provisions',
    labelFr: 'Provisions réglementées',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '141',
    label: 'Provisions for Regulated Depreciation',
    labelFr: 'Provisions pour amortissement dérogatoire',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '145',
    label: 'Provisions for Income Tax Fluctuation',
    labelFr: 'Provisions pour fluctuation des impôts sur le résultat',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '148',
    label: 'Other Regulated Provisions',
    labelFr: 'Autres provisions réglementées',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 15 - PROVISIONS FOR RISKS AND CHARGES
  {
    number: '15',
    label: 'Provisions for Risks and Charges',
    labelFr: 'Provisions pour risques et charges',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '151',
    label: 'Provisions for Risks',
    labelFr: 'Provisions pour risques',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1511',
    label: 'Provisions for Litigation',
    labelFr: 'Provisions pour contentieux',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1512',
    label: 'Provisions for Penalties and Fines',
    labelFr: 'Provisions pour amendes et pénalités',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1513',
    label: 'Provisions for Product Warranty',
    labelFr: 'Provisions pour garanties de produits',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1514',
    label: 'Provisions for Contingent Losses',
    labelFr: 'Provisions pour pertes contingentes',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '152',
    label: 'Provisions for Charges',
    labelFr: 'Provisions pour charges',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1521',
    label: 'Provisions for Restructuring',
    labelFr: 'Provisions pour restructuration',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1522',
    label: 'Provisions for Obligations',
    labelFr: 'Provisions pour obligations',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1523',
    label: 'Provisions for Maintenance and Restoration',
    labelFr: 'Provisions pour entretien et restauration',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1524',
    label: 'Provisions for Major Repairs',
    labelFr: 'Provisions pour grosses réparations',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1525',
    label: 'Provisions for Employee Benefits',
    labelFr: 'Provisions pour avantages aux salariés',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 16 - BORROWINGS AND ASSIMILATED DEBT
  {
    number: '16',
    label: 'Borrowings and Assimilated Debt',
    labelFr: 'Emprunts et dettes assimilées',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '161',
    label: 'Bond Borrowings',
    labelFr: 'Emprunts obligataires',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1611',
    label: 'Bonds Issued at Par',
    labelFr: 'Obligations émises au pair',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1612',
    label: 'Bonds Issued at a Premium',
    labelFr: 'Obligations émises au-dessus du pair',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1613',
    label: 'Bonds Issued at a Discount',
    labelFr: 'Obligations émises au-dessous du pair',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '162',
    label: 'Borrowings from Credit Institutions',
    labelFr: 'Emprunts auprès des établissements de crédit',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1621',
    label: 'Bank Loans',
    labelFr: 'Emprunts bancaires',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1622',
    label: 'Loans from Financial Institutions',
    labelFr: 'Emprunts auprès des établissements financiers',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '163',
    label: 'Advances Received',
    labelFr: 'Avances reçues',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '164',
    label: 'Government Advances Received',
    labelFr: 'Avances reçues de l\'État',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '165',
    label: 'Deposits and Guarantees Received',
    labelFr: 'Dépôts et cautionnements reçus',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '166',
    label: 'Accrued Interest',
    labelFr: 'Intérêts courus',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '167',
    label: 'Advances with Special Conditions',
    labelFr: 'Avances assorties de conditions particulières',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '168',
    label: 'Other Borrowings and Debt',
    labelFr: 'Autres emprunts et dettes',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 17 - LEASING DEBT AND ASSIMILATED CONTRACTS
  {
    number: '17',
    label: 'Leasing Debt and Assimilated Contracts',
    labelFr: 'Dettes de crédit-bail et contrats assimilés',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '172',
    label: 'Movable Leasing Equivalent Debt',
    labelFr: 'Emprunts équivalents de crédit-bail mobilier',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1721',
    label: 'Equipment Leasing Debt',
    labelFr: 'Dettes de crédit-bail équipement',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1722',
    label: 'Vehicle Leasing Debt',
    labelFr: 'Dettes de crédit-bail véhicules',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '173',
    label: 'Real Estate Leasing Equivalent Debt',
    labelFr: 'Emprunts équivalents de crédit-bail immobilier',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1731',
    label: 'Building Leasing Debt',
    labelFr: 'Dettes de crédit-bail immobilier bâtiments',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1732',
    label: 'Land Leasing Debt',
    labelFr: 'Dettes de crédit-bail immobilier terrains',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 18 - DEBTS RELATED TO PARTICIPATIONS AND LIAISON ACCOUNTS
  {
    number: '18',
    label: 'Debts Related to Participations and Liaison Accounts',
    labelFr: 'Dettes liées à des participations et comptes de liaison',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '181',
    label: 'Debts Related to Group Participations',
    labelFr: 'Dettes liées à des participations groupe',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '1811',
    label: 'Loans from Parent Company',
    labelFr: 'Emprunts de la société mère',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '1812',
    label: 'Debts to Group Companies',
    labelFr: 'Dettes envers les sociétés du groupe',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '182',
    label: 'Debts Related to Non-Group Participations',
    labelFr: 'Dettes liées à des participations hors groupe',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '184',
    label: 'Permanent Blocked Accounts',
    labelFr: 'Comptes permanents bloqués',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '185',
    label: 'Associate Current Accounts',
    labelFr: 'Comptes courants associés',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '1851',
    label: 'Associate Current Accounts Credit Balance',
    labelFr: 'Comptes courants associés créditeur',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '1852',
    label: 'Associate Current Accounts Debit Balance',
    labelFr: 'Comptes courants associés débiteur',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },

  // 19 - PROVISIONS FOR RISKS AND CHARGES WITH FINANCIAL CHARACTER
  {
    number: '19',
    label: 'Provisions for Risks and Charges with Financial Character',
    labelFr: 'Provisions pour risques et charges à caractère financier',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '191',
    label: 'Provisions for Financial Risks',
    labelFr: 'Provisions pour risques financiers',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1911',
    label: 'Provisions for Exchange Rate Fluctuation',
    labelFr: 'Provisions pour fluctuation des taux de change',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1912',
    label: 'Provisions for Interest Rate Fluctuation',
    labelFr: 'Provisions pour fluctuation des taux d\'intérêt',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1913',
    label: 'Provisions for Counterparty Risk',
    labelFr: 'Provisions pour risque de contrepartie',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '192',
    label: 'Provisions for Financial Charges',
    labelFr: 'Provisions pour charges financières',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1921',
    label: 'Provisions for Interest on Borrowing',
    labelFr: 'Provisions pour intérêts sur emprunts',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '1922',
    label: 'Provisions for Commitment Commissions',
    labelFr: 'Provisions pour commissions d\'engagement',
    classNumber: 1,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
]

export default CLASSE_1_ACCOUNTS
