import type { Account } from '../../core/types';

export const CLASSE_3_ACCOUNTS: Account[] = [
  // 31 - Marchandises
  {
    accountNumber: '311',
    name: 'Marchandises A',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '312',
    name: 'Marchandises B',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '318',
    name: 'Marchandises hors activités ordinaires',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 32 - Matières premières et fournitures liées
  {
    accountNumber: '321',
    name: 'Matières premières A',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '322',
    name: 'Matières premières B',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '323',
    name: 'Fournitures A',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '324',
    name: 'Fournitures B',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 33 - Autres approvisionnements
  {
    accountNumber: '331',
    name: 'Matières consommables',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '332',
    name: 'Fournitures consommables',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '333',
    name: 'Emballages',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '3351',
    name: 'Emballages perdus',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '3352',
    name: 'Emballages récupérables non identifiables',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '3358',
    name: 'Autres emballages',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '338',
    name: 'Stocks en cours de route, en consignation',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 34 - Produits en cours
  {
    accountNumber: '341',
    name: 'Produits en cours',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '342',
    name: 'Travaux en cours',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '343',
    name: 'Services en cours',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 35 - Services en cours
  {
    accountNumber: '351',
    name: 'Services en cours - Interne',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '352',
    name: 'Services en cours - Externe',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 36 - Produits finis
  {
    accountNumber: '361',
    name: 'Produits finis A',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '362',
    name: 'Produits finis B',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '368',
    name: 'Produits finis hors activités ordinaires',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 37 - Produits intermédiaires et résiduels
  {
    accountNumber: '371',
    name: 'Produits intermédiaires',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '372',
    name: 'Produits résiduels',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '373',
    name: 'Produits intermédiaires hors activités ordinaires',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 38 - Stocks en cours de route, en consignation ou en dépôt
  {
    accountNumber: '381',
    name: 'Stocks en cours de route',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '382',
    name: 'Stocks en consignation',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '383',
    name: 'Stocks en dépôt',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 39 - Dépréciations des stocks
  {
    accountNumber: '391',
    name: 'Dépréciations des marchandises',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '392',
    name: 'Dépréciations des matières premières',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '393',
    name: 'Dépréciations des autres approvisionnements',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '394',
    name: 'Dépréciations des produits en cours',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '395',
    name: 'Dépréciations des services en cours',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '396',
    name: 'Dépréciations des produits finis',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '397',
    name: 'Dépréciations des produits intermédiaires',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '398',
    name: 'Dépréciations des stocks en route',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
];

export default CLASSE_3_ACCOUNTS;
