import type { Account } from '../../core/types';

export const CLASSE_3_ACCOUNTS: Account[] = [
  // 31 - Marchandises
  {
    number: '311',
    labelFr: 'Marchandises A',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '312',
    labelFr: 'Marchandises B',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '318',
    labelFr: 'Marchandises hors activités ordinaires',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 32 - Matières premières et fournitures liées
  {
    number: '321',
    labelFr: 'Matières premières A',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '322',
    labelFr: 'Matières premières B',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '323',
    labelFr: 'Fournitures A',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '324',
    labelFr: 'Fournitures B',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 33 - Autres approvisionnements
  {
    number: '331',
    labelFr: 'Matières consommables',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '332',
    labelFr: 'Fournitures consommables',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '333',
    labelFr: 'Emballages',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '3351',
    labelFr: 'Emballages perdus',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '3352',
    labelFr: 'Emballages récupérables non identifiables',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '3358',
    labelFr: 'Autres emballages',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '338',
    labelFr: 'Stocks en cours de route, en consignation',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 34 - Produits en cours
  {
    number: '341',
    labelFr: 'Produits en cours',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '342',
    labelFr: 'Travaux en cours',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '343',
    labelFr: 'Services en cours',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 35 - Services en cours
  {
    number: '351',
    labelFr: 'Services en cours - Interne',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '352',
    labelFr: 'Services en cours - Externe',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 36 - Produits finis
  {
    number: '361',
    labelFr: 'Produits finis A',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '362',
    labelFr: 'Produits finis B',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '368',
    labelFr: 'Produits finis hors activités ordinaires',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 37 - Produits intermédiaires et résiduels
  {
    number: '371',
    labelFr: 'Produits intermédiaires',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '372',
    labelFr: 'Produits résiduels',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '373',
    labelFr: 'Produits intermédiaires hors activités ordinaires',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 38 - Stocks en cours de route, en consignation ou en dépôt
  {
    number: '381',
    labelFr: 'Stocks en cours de route',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '382',
    labelFr: 'Stocks en consignation',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '383',
    labelFr: 'Stocks en dépôt',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 39 - Dépréciations des stocks
  {
    number: '391',
    labelFr: 'Dépréciations des marchandises',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '392',
    labelFr: 'Dépréciations des matières premières',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '393',
    labelFr: 'Dépréciations des autres approvisionnements',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '394',
    labelFr: 'Dépréciations des produits en cours',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '395',
    labelFr: 'Dépréciations des services en cours',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '396',
    labelFr: 'Dépréciations des produits finis',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '397',
    labelFr: 'Dépréciations des produits intermédiaires',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '398',
    labelFr: 'Dépréciations des stocks en route',
    classNumber: 3,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
];

export default CLASSE_3_ACCOUNTS;
