import type { Account } from '../../core/types';

/**
 * CLASSE 7 SYSCOHADA: Produits des Activités Ordinaires
 * Comptes de produits et revenus
 */
export const CLASSE_7_ACCOUNTS: Account[] = [
  // 70 - VENTES
  {
    accountNumber: '70',
    accountName: 'Ventes',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '701',
    accountName: 'Ventes de marchandises',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '7011',
    accountName: 'Ventes de marchandises A',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '7012',
    accountName: 'Ventes de marchandises B',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '702',
    accountName: 'Ventes de produits finis',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '7021',
    accountName: 'Ventes de produits finis A',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '7022',
    accountName: 'Ventes de produits finis B',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '703',
    accountName: 'Ventes de produits intermédiaires',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '704',
    accountName: 'Ventes de produits résiduels',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '705',
    accountName: 'Travaux facturés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '706',
    accountName: 'Services vendus',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '7061',
    accountName: 'Prestations de services A',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '7062',
    accountName: 'Prestations de services B',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '707',
    accountName: 'Produits accessoires',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '7071',
    accountName: 'Ports, emballages et autres frais facturés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '7072',
    accountName: 'Locations de matériel',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '7073',
    accountName: 'Bonifications obtenues des clients',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '7077',
    accountName: 'Bénéfices attribués par concession',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '7078',
    accountName: 'Autres produits accessoires',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '708',
    accountName: 'Produits des activités annexes',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '709',
    accountName: 'Rabais, remises et ristournes accordés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 71 - SUBVENTIONS D'EXPLOITATION
  {
    accountNumber: '71',
    accountName: 'Subventions d\'exploitation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '711',
    accountName: 'Subventions sur produits importés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '712',
    accountName: 'Subventions sur produits exportés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '713',
    accountName: 'Subventions à l\'importation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '714',
    accountName: 'Subventions au déficit d\'exploitation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '718',
    accountName: 'Autres subventions d\'exploitation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 72 - PRODUCTION IMMOBILISÉE
  {
    accountNumber: '72',
    accountName: 'Production immobilisée',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '721',
    accountName: 'Production immobilisée incorporelle',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '722',
    accountName: 'Production immobilisée corporelle',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 73 - VARIATIONS DES STOCKS
  {
    accountNumber: '73',
    accountName: 'Variations des stocks de biens et services produits',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '734',
    accountName: 'Variations des stocks de produits en cours',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '735',
    accountName: 'Variations des stocks de services en cours',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '736',
    accountName: 'Variations des stocks de produits finis',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '737',
    accountName: 'Variations des stocks de produits intermédiaires et résiduels',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 75 - AUTRES PRODUITS
  {
    accountNumber: '75',
    accountName: 'Autres produits',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '751',
    accountName: 'Produits exceptionnels sur opérations de gestion',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '752',
    accountName: 'Quote-parts de résultats sur opérations faites en commun',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '753',
    accountName: 'Jetons de présence reçus',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '754',
    accountName: 'Produits sur cessions d\'immobilisations courantes',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '758',
    accountName: 'Produits divers',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 76 - FRAIS FINANCIERS ET PRODUITS ASSIMILÉS
  {
    accountNumber: '76',
    accountName: 'Frais financiers et produits assimilés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '761',
    accountName: 'Revenus de placement',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '762',
    accountName: 'Revenus de participations',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '764',
    accountName: 'Revenus de prêts et créances diverses',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '765',
    accountName: 'Escomptes obtenus',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '766',
    accountName: 'Gains de change',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '767',
    accountName: 'Gains sur cessions de titres de placement',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '768',
    accountName: 'Autres frais financiers et produits assimilés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 77 - REVENUS FINANCIERS
  {
    accountNumber: '77',
    accountName: 'Revenus financiers',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '771',
    accountName: 'Revenus de placement',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '772',
    accountName: 'Revenus de participations',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 78 - TRANSFERTS DE CHARGES
  {
    accountNumber: '78',
    accountName: 'Transferts de charges',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '781',
    accountName: 'Transferts de charges d\'exploitation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '787',
    accountName: 'Transferts de charges financières',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 79 - REPRISES DE PROVISIONS
  {
    accountNumber: '79',
    accountName: 'Reprises de provisions',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '791',
    accountName: 'Reprises de provisions d\'exploitation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '797',
    accountName: 'Reprises de provisions financières',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
];
