import type { Account } from '../../core/types';

/**
 * SYSCOHADA CLASSE 5: Comptes de Trésorerie
 *
 * Regroupe les comptes de placements de trésorerie, de valeurs à encaisser,
 * de banques et établissements financiers, de caisse, et des régularisations.
 * Comprend également les comptes de dépréciations et provisions pour risques
 * à court terme.
 */
export const CLASSE_5_ACCOUNTS: Account[] = [
  // CLASSE 50: Titres de placement
  {
    accountNumber: '501',
    accountName: 'Titres du Trésor',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '502',
    accountName: 'Actions',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '503',
    accountName: 'Obligations',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '504',
    accountName: 'Bons de souscription',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '506',
    accountName: 'Intérêts courus sur titres de placement',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '508',
    accountName: 'Autres valeurs assimilées',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '509',
    accountName: 'Titres de placement à libérer',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 51: Valeurs à encaisser
  {
    accountNumber: '511',
    accountName: 'Effets à l\'encaissement',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '512',
    accountName: 'Chèques à encaisser',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '513',
    accountName: 'Effets à l\'escompte',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '514',
    accountName: 'Coupons échus',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '515',
    accountName: 'Cartes de crédit à encaisser',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '518',
    accountName: 'Autres valeurs à l\'encaissement',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 52: Banques
  {
    accountNumber: '521',
    accountName: 'Banques locales',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '522',
    accountName: 'Banques autres États région monétaire',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '523',
    accountName: 'Banques autres États zone monétaire',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '524',
    accountName: 'Banques hors zone monétaire',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '526',
    accountName: 'Banques intérêts courus à recevoir',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '528',
    accountName: 'Banques intérêts courus à payer',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 53: Établissements financiers et assimilés
  {
    accountNumber: '531',
    accountName: 'Chèques postaux',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '532',
    accountName: 'Trésor public',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '533',
    accountName: 'Sociétés de gestion et d\'intermédiation',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '536',
    accountName: 'Établissements financiers intérêts courus à recevoir',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 54: Instruments de monnaie électronique
  {
    accountNumber: '541',
    accountName: 'Instruments de monnaie électronique',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 56: Concours bancaires courants
  {
    accountNumber: '561',
    accountName: 'Crédits de trésorerie',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '564',
    accountName: 'Escompte de crédit ordinaire',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '565',
    accountName: 'Escompte de crédits de mobilisation',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '566',
    accountName: 'Banques crédits de trésorerie',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '568',
    accountName: 'Concours intérêts courus',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 57: Caisse
  {
    accountNumber: '571',
    accountName: 'Caisse siège social',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '572',
    accountName: 'Caisse succursale A',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '573',
    accountName: 'Caisse succursale B',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '578',
    accountName: 'Régies d\'avances et accréditifs',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 58: Régularisations
  {
    accountNumber: '581',
    accountName: 'Virements de fonds',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '582',
    accountName: 'Virements de fonds en attente',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '588',
    accountName: 'Autres virements internes',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 59: Dépréciations et provisions pour risques à court terme
  {
    accountNumber: '591',
    accountName: 'Dépréciations titres de placement',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '592',
    accountName: 'Dépréciations banques',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '599',
    accountName: 'Risques provisionnés',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
];

export default CLASSE_5_ACCOUNTS;
