import type { Account } from '../../core/types'

export const CLASSE_6_ACCOUNTS: Account[] = [
  // 60 - Achats et variations de stocks
  {
    number: '601',
    labelFr: 'Achats de marchandises',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '602',
    labelFr: 'Achats de matières premières et fournitures liées',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '603',
    labelFr: 'Variations des stocks de biens achetés',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '604',
    labelFr: 'Achats stockés de matières et fournitures consommables',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '605',
    labelFr: 'Autres achats',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6051',
    labelFr: 'Fournitures non stockables eau',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6052',
    labelFr: 'Fournitures non stockables électricité',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6053',
    labelFr: 'Carburants',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6054',
    labelFr: 'Produits d\'entretien',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6055',
    labelFr: 'Fournitures de bureau',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6056',
    labelFr: 'Achats de petit matériel',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6057',
    labelFr: 'Achats d\'études et prestations',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6058',
    labelFr: 'Achats de travaux, matériel et équipements',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '608',
    labelFr: 'Achats d\'emballages',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '609',
    labelFr: 'Rabais, remises et ristournes obtenus',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 61 - Transports
  {
    number: '611',
    labelFr: 'Transports sur achats',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '612',
    labelFr: 'Transports sur ventes',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '613',
    labelFr: 'Transports pour le compte de tiers',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '614',
    labelFr: 'Transports du personnel',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '616',
    labelFr: 'Transports plis et correspondances',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '618',
    labelFr: 'Autres frais de transport',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 62 - Services extérieurs A
  {
    number: '621',
    labelFr: 'Sous-traitance générale',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '622',
    labelFr: 'Locations et charges locatives',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '623',
    labelFr: 'Redevances de crédit-bail et contrats assimilés',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '624',
    labelFr: 'Entretien, réparations et maintenance',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '625',
    labelFr: 'Primes d\'assurance',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '626',
    labelFr: 'Études, recherches et documentation',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '627',
    labelFr: 'Publicité, publications, relations publiques',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '628',
    labelFr: 'Frais de télécommunications',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6281',
    labelFr: 'Frais postaux',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6282',
    labelFr: 'Frais de téléphone',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6283',
    labelFr: 'Frais d\'Internet',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 63 - Services extérieurs B
  {
    number: '631',
    labelFr: 'Frais bancaires',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '632',
    labelFr: 'Rémunérations d\'intermédiaires et conseils',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '633',
    labelFr: 'Frais de formation du personnel',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '634',
    labelFr: 'Redevances pour brevets, licences, logiciels',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '635',
    labelFr: 'Cotisations',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '637',
    labelFr: 'Rémunérations du personnel extérieur',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '638',
    labelFr: 'Autres charges externes',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 64 - Impôts et taxes
  {
    number: '641',
    labelFr: 'Impôts et taxes directs',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6411',
    labelFr: 'Impôts fonciers',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6412',
    labelFr: 'Taxes professionnelles',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6413',
    labelFr: 'Patente',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6414',
    labelFr: 'Licences',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '645',
    labelFr: 'Autres impôts et taxes',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '646',
    labelFr: 'Droits d\'enregistrement',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 65 - Autres charges
  {
    number: '651',
    labelFr: 'Pertes sur créances clients',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '652',
    labelFr: 'Quote-parts de résultats sur opérations faites en commun',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '653',
    labelFr: 'Jetons de présence',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '654',
    labelFr: 'Pertes sur cessions d\'immobilisations courantes',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '658',
    labelFr: 'Charges diverses',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 66 - Charges de personnel
  {
    number: '661',
    labelFr: 'Rémunérations directes versées au personnel national',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '662',
    labelFr: 'Rémunérations directes versées au personnel non national',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '663',
    labelFr: 'Indemnités forfaitaires',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '664',
    labelFr: 'Charges sociales',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6641',
    labelFr: 'Charges sociales sur rémunération du personnel national',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6642',
    labelFr: 'Charges sociales sur rémunération du personnel non national',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6648',
    labelFr: 'Autres charges sociales',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '666',
    labelFr: 'Rémunérations et charges des dirigeants',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '667',
    labelFr: 'Rémunérations transférées de personnel extérieur',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '668',
    labelFr: 'Autres charges sociales',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 67 - Frais financiers et charges assimilées
  {
    number: '671',
    labelFr: 'Intérêts des emprunts',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '672',
    labelFr: 'Intérêts dans loyers de crédit-bail',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '674',
    labelFr: 'Autres intérêts',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '675',
    labelFr: 'Escomptes accordés',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '676',
    labelFr: 'Pertes de change',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '677',
    labelFr: 'Pertes sur cessions de titres de placement',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '678',
    labelFr: 'Autres frais financiers',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 68 - Dotations aux amortissements
  {
    number: '681',
    labelFr: 'Dotations aux amortissements d\'exploitation',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6811',
    labelFr: 'Dotations aux amortissements des immobilisations incorporelles',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6812',
    labelFr: 'Dotations aux amortissements des immobilisations corporelles',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6813',
    labelFr: 'Dotations aux amortissements des charges immobilisées',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '687',
    labelFr: 'Dotations aux amortissements à caractère financier',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6871',
    labelFr: 'Dotations aux amortissements financiers 1',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '6872',
    labelFr: 'Dotations aux amortissements financiers 2',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 69 - Dotations aux provisions
  {
    number: '691',
    labelFr: 'Dotations aux provisions d\'exploitation',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '697',
    labelFr: 'Dotations aux provisions financières',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
]
