import type { Account } from '../../core/types'

export const CLASSE_4_ACCOUNTS: Account[] = [
  // 40 - FOURNISSEURS ET COMPTES RATTACHÉS
  {
    number: '40',
    label: 'Suppliers and Related Accounts',
    labelFr: 'Fournisseurs et comptes rattachés',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '401',
    label: 'Suppliers',
    labelFr: 'Fournisseurs',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: true,
    normalBalance: 'CREDIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '4011',
    label: 'Supplier Accounts Payable',
    labelFr: 'Fournisseurs dettes en compte',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: true,
    normalBalance: 'CREDIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
    parentAccount: '401',
  },
  {
    number: '402',
    label: 'Supplier Bills Payable',
    labelFr: 'Fournisseurs effets à payer',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '408',
    label: 'Supplier Invoices Not Received',
    labelFr: 'Fournisseurs factures non parvenues',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '409',
    label: 'Supplier Debit Accounts',
    labelFr: 'Fournisseurs débiteurs',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 41 - CLIENTS ET COMPTES RATTACHÉS
  {
    number: '41',
    label: 'Customers and Related Accounts',
    labelFr: 'Clients et comptes rattachés',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '411',
    label: 'Customers',
    labelFr: 'Clients',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: true,
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '4111',
    label: 'Customer Invoices',
    labelFr: 'Clients factures',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: true,
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
    parentAccount: '411',
  },
  {
    number: '412',
    label: 'Customer Bills Receivable',
    labelFr: 'Clients effets à recevoir',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '414',
    label: 'Doubtful or Disputed Customers',
    labelFr: 'Clients douteux ou litigieux',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '416',
    label: 'Customer Disputed Receivables',
    labelFr: 'Créances clients litigieuses',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '418',
    label: 'Customer Products to Receive',
    labelFr: 'Clients produits à recevoir',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '419',
    label: 'Customer Credit Accounts',
    labelFr: 'Clients créditeurs',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: true,
    normalBalance: 'CREDIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },

  // 42 - PERSONNEL
  {
    number: '42',
    label: 'Personnel',
    labelFr: 'Personnel',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '421',
    label: 'Personnel Advances',
    labelFr: 'Personnel avances',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: true,
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '422',
    label: 'Personnel Salaries Due',
    labelFr: 'Personnel rémunérations dues',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '423',
    label: 'Personnel Salary Garnishments',
    labelFr: 'Personnel oppositions',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '424',
    label: 'Personnel Social Benefits',
    labelFr: 'Personnel oeuvres sociales',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '425',
    label: 'Personnel Representatives',
    labelFr: 'Représentants du personnel',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '426',
    label: 'Personnel Charges to Pay',
    labelFr: 'Personnel charges à payer',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '427',
    label: 'Personnel Deposits',
    labelFr: 'Personnel dépôts',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '428',
    label: 'Personnel Charges to Pay and Income to Receive',
    labelFr: 'Personnel charges à payer et produits à recevoir',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 43 - ORGANISMES SOCIAUX
  {
    number: '43',
    label: 'Social Organizations',
    labelFr: 'Organismes sociaux',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '431',
    label: 'Social Security / CNSS',
    labelFr: 'CNSS / Sécurité sociale',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '432',
    label: 'Supplemental Pension Funds',
    labelFr: 'Caisses retraite complémentaire',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '433',
    label: 'Other Social Organizations',
    labelFr: 'Autres organismes sociaux',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '438',
    label: 'Social Organizations Charges to Pay',
    labelFr: 'Organismes sociaux charges à payer',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 44 - ÉTAT ET COLLECTIVITÉS PUBLIQUES
  {
    number: '44',
    label: 'Government and Public Authorities',
    labelFr: 'État et collectivités publiques',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '441',
    label: 'Income Tax Payable',
    labelFr: 'État impôt sur le résultat',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '442',
    label: 'Other Taxes Payable',
    labelFr: 'État autres impôts et taxes',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '443',
    label: 'VAT Collected',
    labelFr: 'État TVA collectée',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '4431',
    label: 'VAT Collected - Sales',
    labelFr: 'TVA collectée',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
    parentAccount: '443',
  },
  {
    number: '4432',
    label: 'VAT Recoverable on Fixed Assets',
    labelFr: 'TVA récupérable sur immobilisations',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
    parentAccount: '443',
  },
  {
    number: '4433',
    label: 'VAT Recoverable on Goods and Services',
    labelFr: 'TVA récupérable sur autres biens et services',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
    parentAccount: '443',
  },
  {
    number: '445',
    label: 'VAT Payable / VAT Credit',
    labelFr: 'État TVA à payer/crédit',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '4451',
    label: 'VAT Due to Pay',
    labelFr: 'TVA due',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
    parentAccount: '445',
  },
  {
    number: '4452',
    label: 'VAT Credit',
    labelFr: 'TVA crédit',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
    parentAccount: '445',
  },
  {
    number: '446',
    label: 'Other Government Taxes and Rights',
    labelFr: 'État autres droits et taxes',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '447',
    label: 'Withholding Taxes Withheld',
    labelFr: 'État impôts retenus à la source',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '449',
    label: 'Government Charges to Pay and Income to Receive',
    labelFr: 'État charges à payer et produits à recevoir',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 45 - ORGANISMES INTERNATIONAUX
  {
    number: '45',
    label: 'International Organizations',
    labelFr: 'Organismes internationaux',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '451',
    label: 'International Organization Payables',
    labelFr: 'Organismes internationaux dettes',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '452',
    label: 'International Organization Receivables',
    labelFr: 'Organismes internationaux créances',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 46 - ASSOCIÉS ET GROUPE
  {
    number: '46',
    label: 'Associates and Group',
    labelFr: 'Associés et groupe',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '461',
    label: 'Associates Current Accounts',
    labelFr: 'Associés comptes courants',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '462',
    label: 'Associates Capital Operations',
    labelFr: 'Associés opérations sur capital',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '463',
    label: 'Associates Joint Operations',
    labelFr: 'Associés opérations faites en commun',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '464',
    label: 'Associates Dividends Payable',
    labelFr: 'Associés dividendes à payer',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '465',
    label: 'Associates Capital to Reimburse',
    labelFr: 'Associés capitaux à rembourser',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '466',
    label: 'Group',
    labelFr: 'Groupe',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '467',
    label: 'Associates Current Accounts',
    labelFr: 'Comptes courants des associés',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '468',
    label: 'Associates Charges to Pay',
    labelFr: 'Associés charges à payer',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 47 - DÉBITEURS ET CRÉDITEURS DIVERS
  {
    number: '47',
    label: 'Miscellaneous Debtors and Creditors',
    labelFr: 'Débiteurs et créditeurs divers',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '471',
    label: 'Clearing Account',
    labelFr: 'Compte d\'attente',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '472',
    label: 'Payments to Be Made',
    labelFr: 'Versements restant à effectuer',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '473',
    label: 'Transfers to Classify',
    labelFr: 'Transferts à classer',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '474',
    label: 'Periodic Allocation of Expenses',
    labelFr: 'Répartition périodique des charges',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '475',
    label: 'Expenses to Allocate',
    labelFr: 'Frais à étaler',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '476',
    label: 'Prepaid Expenses',
    labelFr: 'Charges constatées d\'avance',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '477',
    label: 'Deferred Revenue',
    labelFr: 'Produits constatés d\'avance',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '478',
    label: 'Exchange Differences',
    labelFr: 'Écarts de conversion actif/passif',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '4781',
    label: 'Exchange Differences - Asset',
    labelFr: 'Écarts de conversion actif',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
    parentAccount: '478',
  },
  {
    number: '4782',
    label: 'Exchange Differences - Liability',
    labelFr: 'Écarts de conversion passif',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
    parentAccount: '478',
  },
  {
    number: '479',
    label: 'Transitional Account',
    labelFr: 'Compte transitoire',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 48 - CRÉANCES ET DETTES HORS ACTIVITÉS ORDINAIRES
  {
    number: '48',
    label: 'Non-Operating Receivables and Payables',
    labelFr: 'Créances et dettes hors activités ordinaires',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '481',
    label: 'Non-Operating Receivables',
    labelFr: 'Créances hors activités ordinaires',
    classNumber: 4,
    category: 'BALANCE_SHEET_ASSET',
    isAuxiliary: false,
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '482',
    label: 'Non-Operating Payables',
    labelFr: 'Dettes hors activités ordinaires',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '488',
    label: 'Non-Operating Charges to Pay and Income to Receive',
    labelFr: 'Charges à payer et produits à recevoir hors activités ordinaires',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 49 - DÉPRÉCIATIONS ET RISQUES PROVISIONNÉS SUR TIERS
  {
    number: '49',
    label: 'Allowances and Provisions on Third Parties',
    labelFr: 'Dépréciations et risques provisionnés sur tiers',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '491',
    label: 'Allowance for Doubtful Customers',
    labelFr: 'Dépréciations clients',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '492',
    label: 'Allowance for Personnel',
    labelFr: 'Dépréciations personnel',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '493',
    label: 'Allowance for Social Organizations',
    labelFr: 'Dépréciations organismes sociaux',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '494',
    label: 'Allowance for Government',
    labelFr: 'Dépréciations État',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '496',
    label: 'Allowance for Associates',
    labelFr: 'Dépréciations associés',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '497',
    label: 'Allowance for Miscellaneous Debtors',
    labelFr: 'Dépréciations débiteurs divers',
    classNumber: 4,
    category: 'BALANCE_SHEET_LIABILITY',
    isAuxiliary: false,
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
]

export default CLASSE_4_ACCOUNTS
