import type { Account } from '../../core/types'

/**
 * CLASSE 8 SYSCOHADA: "Autres Charges et Autres Produits" (Hors Activités Ordinaires HAO)
 *
 * Cette classe regroupe les comptes relatifs aux opérations hors activités ordinaires,
 * incluant les cessions d'immobilisations, les charges et produits HAO, ainsi que
 * les dotations, reprises, participations et impôts sur le résultat.
 */

export const CLASSE_8_ACCOUNTS: Account[] = [
  // CLASSE 81: Valeurs comptables des cessions d'immobilisations
  {
    accountNumber: '81',
    accountName: 'Valeurs comptables des cessions d\'immobilisations',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '812',
    accountName: 'Valeurs comptables des cessions d\'immobilisations incorporelles',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '813',
    accountName: 'Valeurs comptables des cessions d\'immobilisations corporelles',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '816',
    accountName: 'Valeurs comptables des cessions d\'immobilisations financières',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 82: Produits des cessions d'immobilisations
  {
    accountNumber: '82',
    accountName: 'Produits des cessions d\'immobilisations',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '822',
    accountName: 'Produits des cessions d\'immobilisations incorporelles',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '823',
    accountName: 'Produits des cessions d\'immobilisations corporelles',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '826',
    accountName: 'Produits des cessions d\'immobilisations financières',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 83: Charges hors activités ordinaires
  {
    accountNumber: '83',
    accountName: 'Charges hors activités ordinaires',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '831',
    accountName: 'Charges HAO constatées',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '832',
    accountName: 'Pertes sur risques HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '835',
    accountName: 'Dons et libéralités accordés',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '836',
    accountName: 'Abandons de créances consentis',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '838',
    accountName: 'Charges HAO diverses',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 84: Produits hors activités ordinaires
  {
    accountNumber: '84',
    accountName: 'Produits hors activités ordinaires',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '841',
    accountName: 'Produits HAO constatés',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '845',
    accountName: 'Dons et libéralités obtenus',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '846',
    accountName: 'Abandons de créances obtenus',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '848',
    accountName: 'Produits HAO divers',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 85: Dotations HAO
  {
    accountNumber: '85',
    accountName: 'Dotations HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '851',
    accountName: 'Dotations aux provisions réglementées',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '852',
    accountName: 'Dotations aux amortissements HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '853',
    accountName: 'Dotations aux provisions HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '858',
    accountName: 'Autres dotations HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 86: Reprises HAO
  {
    accountNumber: '86',
    accountName: 'Reprises HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '861',
    accountName: 'Reprises de provisions réglementées',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '862',
    accountName: 'Reprises d\'amortissements HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '863',
    accountName: 'Reprises de provisions HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '868',
    accountName: 'Autres reprises HAO',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 87: Participation des travailleurs
  {
    accountNumber: '87',
    accountName: 'Participation des travailleurs',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '871',
    accountName: 'Participation légale aux bénéfices',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 88: Subventions d'équilibre
  {
    accountNumber: '88',
    accountName: 'Subventions d\'équilibre',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '881',
    accountName: 'Subventions d\'équilibre reçues',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '882',
    accountName: 'Subventions d\'équilibre versées',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },

  // CLASSE 89: Impôts sur le résultat
  {
    accountNumber: '89',
    accountName: 'Impôts sur le résultat',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '891',
    accountName: 'Impôts sur les bénéfices de l\'exercice',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '892',
    accountName: 'Rappels d\'impôts sur résultats antérieurs',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '895',
    accountName: 'Crédit d\'impôt',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
  {
    accountNumber: '899',
    accountName: 'Impôts sur le résultat - participation',
    classNumber: 8,
    jurisdiction: 'OHADA',
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
  },
]

export default CLASSE_8_ACCOUNTS
