import type { Account } from '../../core/types'

export const CLASSE_6_ACCOUNTS: Account[] = [
  // 60 - Achats et variations de stocks
  {
    accountNumber: '601',
    accountName: 'Achats de marchandises',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '602',
    accountName: 'Achats de matières premières et fournitures liées',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '603',
    accountName: 'Variations des stocks de biens achetés',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '604',
    accountName: 'Achats stockés de matières et fournitures consommables',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '605',
    accountName: 'Autres achats',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6051',
    accountName: 'Fournitures non stockables eau',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6052',
    accountName: 'Fournitures non stockables électricité',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6053',
    accountName: 'Carburants',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6054',
    accountName: 'Produits d\'entretien',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6055',
    accountName: 'Fournitures de bureau',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6056',
    accountName: 'Achats de petit matériel',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6057',
    accountName: 'Achats d\'études et prestations',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6058',
    accountName: 'Achats de travaux, matériel et équipements',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '608',
    accountName: 'Achats d\'emballages',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '609',
    accountName: 'Rabais, remises et ristournes obtenus',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 61 - Transports
  {
    accountNumber: '611',
    accountName: 'Transports sur achats',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '612',
    accountName: 'Transports sur ventes',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '613',
    accountName: 'Transports pour le compte de tiers',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '614',
    accountName: 'Transports du personnel',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '616',
    accountName: 'Transports plis et correspondances',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '618',
    accountName: 'Autres frais de transport',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 62 - Services extérieurs A
  {
    accountNumber: '621',
    accountName: 'Sous-traitance générale',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '622',
    accountName: 'Locations et charges locatives',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '623',
    accountName: 'Redevances de crédit-bail et contrats assimilés',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '624',
    accountName: 'Entretien, réparations et maintenance',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '625',
    accountName: 'Primes d\'assurance',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '626',
    accountName: 'Études, recherches et documentation',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '627',
    accountName: 'Publicité, publications, relations publiques',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '628',
    accountName: 'Frais de télécommunications',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6281',
    accountName: 'Frais postaux',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6282',
    accountName: 'Frais de téléphone',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6283',
    accountName: 'Frais d\'Internet',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 63 - Services extérieurs B
  {
    accountNumber: '631',
    accountName: 'Frais bancaires',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '632',
    accountName: 'Rémunérations d\'intermédiaires et conseils',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '633',
    accountName: 'Frais de formation du personnel',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '634',
    accountName: 'Redevances pour brevets, licences, logiciels',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '635',
    accountName: 'Cotisations',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '637',
    accountName: 'Rémunérations du personnel extérieur',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '638',
    accountName: 'Autres charges externes',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 64 - Impôts et taxes
  {
    accountNumber: '641',
    accountName: 'Impôts et taxes directs',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6411',
    accountName: 'Impôts fonciers',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6412',
    accountName: 'Taxes professionnelles',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6413',
    accountName: 'Patente',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6414',
    accountName: 'Licences',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '645',
    accountName: 'Autres impôts et taxes',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '646',
    accountName: 'Droits d\'enregistrement',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 65 - Autres charges
  {
    accountNumber: '651',
    accountName: 'Pertes sur créances clients',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '652',
    accountName: 'Quote-parts de résultats sur opérations faites en commun',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '653',
    accountName: 'Jetons de présence',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '654',
    accountName: 'Pertes sur cessions d\'immobilisations courantes',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '658',
    accountName: 'Charges diverses',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 66 - Charges de personnel
  {
    accountNumber: '661',
    accountName: 'Rémunérations directes versées au personnel national',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '662',
    accountName: 'Rémunérations directes versées au personnel non national',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '663',
    accountName: 'Indemnités forfaitaires',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '664',
    accountName: 'Charges sociales',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6641',
    accountName: 'Charges sociales sur rémunération du personnel national',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6642',
    accountName: 'Charges sociales sur rémunération du personnel non national',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6648',
    accountName: 'Autres charges sociales',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '666',
    accountName: 'Rémunérations et charges des dirigeants',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '667',
    accountName: 'Rémunérations transférées de personnel extérieur',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '668',
    accountName: 'Autres charges sociales',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 67 - Frais financiers et charges assimilées
  {
    accountNumber: '671',
    accountName: 'Intérêts des emprunts',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '672',
    accountName: 'Intérêts dans loyers de crédit-bail',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '674',
    accountName: 'Autres intérêts',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '675',
    accountName: 'Escomptes accordés',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '676',
    accountName: 'Pertes de change',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '677',
    accountName: 'Pertes sur cessions de titres de placement',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '678',
    accountName: 'Autres frais financiers',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 68 - Dotations aux amortissements
  {
    accountNumber: '681',
    accountName: 'Dotations aux amortissements d\'exploitation',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6811',
    accountName: 'Dotations aux amortissements des immobilisations incorporelles',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6812',
    accountName: 'Dotations aux amortissements des immobilisations corporelles',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6813',
    accountName: 'Dotations aux amortissements des charges immobilisées',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '687',
    accountName: 'Dotations aux amortissements à caractère financier',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6871',
    accountName: 'Dotations aux amortissements financiers 1',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '6872',
    accountName: 'Dotations aux amortissements financiers 2',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  // 69 - Dotations aux provisions
  {
    accountNumber: '691',
    accountName: 'Dotations aux provisions d\'exploitation',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    accountNumber: '697',
    accountName: 'Dotations aux provisions financières',
    classNumber: 6,
    category: 'INCOME_STATEMENT_EXPENSE',
    normalBalance: 'DEBIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
]
