import type { Account } from '../../core/types';

/**
 * SYSCOHADA CLASSE 5: Comptes de Trésorerie
 *
 * Regroupe les comptes de placements de trésorerie, de valeurs à encaisser,
 * de banques et établissements financiers, de caisse, et des régularisations.
 * Comprend également les comptes de dépréciations et provisions pour risques
 * à court terme.
 */
export const CLASSE_5_ACCOUNTS: Account[] = [
  // CLASSE 50: Titres de placement
  {
    number: '501',
    labelFr: 'Titres du Trésor',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '502',
    labelFr: 'Actions',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '503',
    labelFr: 'Obligations',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '504',
    labelFr: 'Bons de souscription',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '506',
    labelFr: 'Intérêts courus sur titres de placement',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '508',
    labelFr: 'Autres valeurs assimilées',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '509',
    labelFr: 'Titres de placement à libérer',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 51: Valeurs à encaisser
  {
    number: '511',
    labelFr: 'Effets à l\'encaissement',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '512',
    labelFr: 'Chèques à encaisser',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '513',
    labelFr: 'Effets à l\'escompte',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '514',
    labelFr: 'Coupons échus',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '515',
    labelFr: 'Cartes de crédit à encaisser',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '518',
    labelFr: 'Autres valeurs à l\'encaissement',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 52: Banques
  {
    number: '521',
    labelFr: 'Banques locales',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '522',
    labelFr: 'Banques autres États région monétaire',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '523',
    labelFr: 'Banques autres États zone monétaire',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '524',
    labelFr: 'Banques hors zone monétaire',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '526',
    labelFr: 'Banques intérêts courus à recevoir',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '528',
    labelFr: 'Banques intérêts courus à payer',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 53: Établissements financiers et assimilés
  {
    number: '531',
    labelFr: 'Chèques postaux',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '532',
    labelFr: 'Trésor public',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '533',
    labelFr: 'Sociétés de gestion et d\'intermédiation',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '536',
    labelFr: 'Établissements financiers intérêts courus à recevoir',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 54: Instruments de monnaie électronique
  {
    number: '541',
    labelFr: 'Instruments de monnaie électronique',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 56: Concours bancaires courants
  {
    number: '561',
    labelFr: 'Crédits de trésorerie',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '564',
    labelFr: 'Escompte de crédit ordinaire',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '565',
    labelFr: 'Escompte de crédits de mobilisation',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '566',
    labelFr: 'Banques crédits de trésorerie',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '568',
    labelFr: 'Concours intérêts courus',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 57: Caisse
  {
    number: '571',
    labelFr: 'Caisse siège social',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: true,
    jurisdiction: 'OHADA',
  },
  {
    number: '572',
    labelFr: 'Caisse succursale A',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '573',
    labelFr: 'Caisse succursale B',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '578',
    labelFr: 'Régies d\'avances et accréditifs',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 58: Régularisations
  {
    number: '581',
    labelFr: 'Virements de fonds',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '582',
    labelFr: 'Virements de fonds en attente',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '588',
    labelFr: 'Autres virements internes',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'DEBIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // CLASSE 59: Dépréciations et provisions pour risques à court terme
  {
    number: '591',
    labelFr: 'Dépréciations titres de placement',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '592',
    labelFr: 'Dépréciations banques',
    classNumber: 5,
    category: 'BALANCE_SHEET_ASSET',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '599',
    labelFr: 'Risques provisionnés',
    classNumber: 5,
    category: 'BALANCE_SHEET_LIABILITY',
    normalBalance: 'CREDIT',
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
];

export default CLASSE_5_ACCOUNTS;
