import type { Account } from '../../core/types';

/**
 * CLASSE 7 SYSCOHADA: Produits des Activités Ordinaires
 * Comptes de produits et revenus
 */
export const CLASSE_7_ACCOUNTS: Account[] = [
  // 70 - VENTES
  {
    number: '70',
    labelFr: 'Ventes',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '701',
    labelFr: 'Ventes de marchandises',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '7011',
    labelFr: 'Ventes de marchandises A',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '7012',
    labelFr: 'Ventes de marchandises B',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '702',
    labelFr: 'Ventes de produits finis',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '7021',
    labelFr: 'Ventes de produits finis A',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '7022',
    labelFr: 'Ventes de produits finis B',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '703',
    labelFr: 'Ventes de produits intermédiaires',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '704',
    labelFr: 'Ventes de produits résiduels',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '705',
    labelFr: 'Travaux facturés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '706',
    labelFr: 'Services vendus',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '7061',
    labelFr: 'Prestations de services A',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '7062',
    labelFr: 'Prestations de services B',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '707',
    labelFr: 'Produits accessoires',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '7071',
    labelFr: 'Ports, emballages et autres frais facturés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '7072',
    labelFr: 'Locations de matériel',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '7073',
    labelFr: 'Bonifications obtenues des clients',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '7077',
    labelFr: 'Bénéfices attribués par concession',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '7078',
    labelFr: 'Autres produits accessoires',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '708',
    labelFr: 'Produits des activités annexes',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '709',
    labelFr: 'Rabais, remises et ristournes accordés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 71 - SUBVENTIONS D'EXPLOITATION
  {
    number: '71',
    labelFr: 'Subventions d\'exploitation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '711',
    labelFr: 'Subventions sur produits importés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '712',
    labelFr: 'Subventions sur produits exportés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '713',
    labelFr: 'Subventions à l\'importation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '714',
    labelFr: 'Subventions au déficit d\'exploitation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '718',
    labelFr: 'Autres subventions d\'exploitation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 72 - PRODUCTION IMMOBILISÉE
  {
    number: '72',
    labelFr: 'Production immobilisée',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '721',
    labelFr: 'Production immobilisée incorporelle',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '722',
    labelFr: 'Production immobilisée corporelle',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 73 - VARIATIONS DES STOCKS
  {
    number: '73',
    labelFr: 'Variations des stocks de biens et services produits',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '734',
    labelFr: 'Variations des stocks de produits en cours',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '735',
    labelFr: 'Variations des stocks de services en cours',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '736',
    labelFr: 'Variations des stocks de produits finis',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '737',
    labelFr: 'Variations des stocks de produits intermédiaires et résiduels',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 75 - AUTRES PRODUITS
  {
    number: '75',
    labelFr: 'Autres produits',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '751',
    labelFr: 'Produits exceptionnels sur opérations de gestion',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '752',
    labelFr: 'Quote-parts de résultats sur opérations faites en commun',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '753',
    labelFr: 'Jetons de présence reçus',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '754',
    labelFr: 'Produits sur cessions d\'immobilisations courantes',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '758',
    labelFr: 'Produits divers',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 76 - FRAIS FINANCIERS ET PRODUITS ASSIMILÉS
  {
    number: '76',
    labelFr: 'Frais financiers et produits assimilés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '761',
    labelFr: 'Revenus de placement',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '762',
    labelFr: 'Revenus de participations',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '764',
    labelFr: 'Revenus de prêts et créances diverses',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '765',
    labelFr: 'Escomptes obtenus',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '766',
    labelFr: 'Gains de change',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '767',
    labelFr: 'Gains sur cessions de titres de placement',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '768',
    labelFr: 'Autres frais financiers et produits assimilés',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 77 - REVENUS FINANCIERS
  {
    number: '77',
    labelFr: 'Revenus financiers',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '771',
    labelFr: 'Revenus de placement',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '772',
    labelFr: 'Revenus de participations',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 78 - TRANSFERTS DE CHARGES
  {
    number: '78',
    labelFr: 'Transferts de charges',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '781',
    labelFr: 'Transferts de charges d\'exploitation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '787',
    labelFr: 'Transferts de charges financières',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },

  // 79 - REPRISES DE PROVISIONS
  {
    number: '79',
    labelFr: 'Reprises de provisions',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '791',
    labelFr: 'Reprises de provisions d\'exploitation',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
  {
    number: '797',
    labelFr: 'Reprises de provisions financières',
    classNumber: 7,
    category: 'INCOME_STATEMENT_REVENUE',
    normalBalance: 'CREDIT',
    isAuxiliary: false,
    isReconcilable: false,
    jurisdiction: 'OHADA',
  },
];
