-- 040: Extended employee fields matching Payroll Mauritius form
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS common_name TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS maiden_name TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS is_mauritian BOOLEAN DEFAULT TRUE;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS gender TEXT DEFAULT 'M' CHECK (gender IN ('M', 'F'));
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS date_naissance DATE;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS statut_familial TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS education TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS badge_number TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS address_2 TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS postcode TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS mobile TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS date_poste_actuel DATE;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS type_contrat TEXT DEFAULT 'fulltime' CHECK (type_contrat IN ('fulltime', 'parttime', 'casual', 'fixed_term'));
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS office_site TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS supervisor_id UUID REFERENCES public.employes(id);
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS working_days JSONB DEFAULT '{"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":false,"sun":false}';
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS departure_type TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS departure_reason TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS suspension_date DATE;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS suspension_reason TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS contribution_code TEXT DEFAULT 'S2';
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS nsf_csg_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS paye_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS edf_total_deduction NUMERIC(15,2) DEFAULT 0;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS paid_by_bank_transfer BOOLEAN DEFAULT TRUE;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS phone_allowance NUMERIC(15,2) DEFAULT 0;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS daily_bus_fare NUMERIC(15,2) DEFAULT 0;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS prime_trimestrielle NUMERIC(15,2) DEFAULT 0;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS it_equipment TEXT;
ALTER TABLE public.employes ADD COLUMN IF NOT EXISTS internet_device TEXT;
