-- ============================================================================
-- Migration 214 — ABANDONNÉE — voir migration 215
-- ============================================================================
--
-- La version initiale de cette migration ajoutait deux INSERT séparés sur 6411
-- (un débit "Salaire base" + un crédit "Retenue UL/absence") pour gérer les
-- déductions d'unpaid leave et d'absence. Elle violait la contrainte unique
-- `ux_ecritures_v2_ref_folio` (societe_id, ref_folio, numero_compte) — il ne
-- peut y avoir qu'une seule ligne par compte/folio.
--
-- La migration 215 remplace cette approche par un netting (débit unique sur
-- 6411 = salaire_base − montant_ul − montant_absence). Le contenu de cette
-- migration a été vidé pour éviter d'écraser la fonction par une version
-- buguée si la chaîne complète est rejouée sur une nouvelle base.
--
-- Conservée comme trace historique. No-op intentionnel.
-- ============================================================================

-- (Aucune instruction SQL — voir migration 215.)
