-- ============================================================================
-- Migration 218 — DÉSACTIVÉE (no-op) — voir migration 219
-- ============================================================================
--
-- La version initiale de cette migration créait :
--   • une fonction `user_can_access_societe(uuid)` SECURITY DEFINER
--   • des policies tenant sur factures, ecritures_comptables_v2 et tables RH
--
-- À l'inspection prod :
--   • Une fonction `user_has_societe_access(uuid)` existe déjà et est
--     utilisée par les policies `factures_tenant_*`, `ecritures_v2_tenant_*`,
--     `releves_tenant_*`, `comptes_bancaires_tenant_*` qui sont DÉJÀ
--     correctement scopées.
--   • Recréer une fonction parallèle créerait du code mort, et recréer les
--     policies sur factures/ecritures_v2 ferait planter la migration
--     (CREATE POLICY rejette si policy de même nom existe).
--
-- Le travail RH (qui était P0 réel : tables `employes`, `bulletins_paie`,
-- `contrats_employes`, `conges_employes` non scopées par société) est
-- déplacé vers la migration 219, qui réutilise `user_has_societe_access`
-- au lieu de réinventer la fonction.
--
-- Conservée comme trace historique. No-op intentionnel.
-- ============================================================================

-- (Aucune instruction SQL — voir migration 219.)
